require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BetaController do

  # This should return the minimal set of attributes required to create a valid
  # Betum. As you add validations to Betum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BetaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all beta as @beta" do
      betum = Betum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:beta).should eq([betum])
    end
  end

  describe "GET show" do
    it "assigns the requested betum as @betum" do
      betum = Betum.create! valid_attributes
      get :show, {:id => betum.to_param}, valid_session
      assigns(:betum).should eq(betum)
    end
  end

  describe "GET new" do
    it "assigns a new betum as @betum" do
      get :new, {}, valid_session
      assigns(:betum).should be_a_new(Betum)
    end
  end

  describe "GET edit" do
    it "assigns the requested betum as @betum" do
      betum = Betum.create! valid_attributes
      get :edit, {:id => betum.to_param}, valid_session
      assigns(:betum).should eq(betum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Betum" do
        expect {
          post :create, {:betum => valid_attributes}, valid_session
        }.to change(Betum, :count).by(1)
      end

      it "assigns a newly created betum as @betum" do
        post :create, {:betum => valid_attributes}, valid_session
        assigns(:betum).should be_a(Betum)
        assigns(:betum).should be_persisted
      end

      it "redirects to the created betum" do
        post :create, {:betum => valid_attributes}, valid_session
        response.should redirect_to(Betum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved betum as @betum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Betum.any_instance.stub(:save).and_return(false)
        post :create, {:betum => { "name" => "invalid value" }}, valid_session
        assigns(:betum).should be_a_new(Betum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Betum.any_instance.stub(:save).and_return(false)
        post :create, {:betum => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested betum" do
        betum = Betum.create! valid_attributes
        # Assuming there are no other beta in the database, this
        # specifies that the Betum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Betum.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => betum.to_param, :betum => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested betum as @betum" do
        betum = Betum.create! valid_attributes
        put :update, {:id => betum.to_param, :betum => valid_attributes}, valid_session
        assigns(:betum).should eq(betum)
      end

      it "redirects to the betum" do
        betum = Betum.create! valid_attributes
        put :update, {:id => betum.to_param, :betum => valid_attributes}, valid_session
        response.should redirect_to(betum)
      end
    end

    describe "with invalid params" do
      it "assigns the betum as @betum" do
        betum = Betum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Betum.any_instance.stub(:save).and_return(false)
        put :update, {:id => betum.to_param, :betum => { "name" => "invalid value" }}, valid_session
        assigns(:betum).should eq(betum)
      end

      it "re-renders the 'edit' template" do
        betum = Betum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Betum.any_instance.stub(:save).and_return(false)
        put :update, {:id => betum.to_param, :betum => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested betum" do
      betum = Betum.create! valid_attributes
      expect {
        delete :destroy, {:id => betum.to_param}, valid_session
      }.to change(Betum, :count).by(-1)
    end

    it "redirects to the beta list" do
      betum = Betum.create! valid_attributes
      delete :destroy, {:id => betum.to_param}, valid_session
      response.should redirect_to(beta_url)
    end
  end

end
